name = "RepeatArrays"
uuid = "9a1e7264-5987-485a-8342-3482f39a2cc3"
authors = ["Jack Coughlin <jack@jackc.me> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
